apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: gateway-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: oauth2gateway.jberger.github.io/v1alpha1
    resource: gateways
  childResources:
    - apiVersion: v1
      resource: pods
      updateStrategy:
        method: Recreate
    - apiVersion: v1
      resource: services
      updateStrategy:
        method: InPlace
  hooks:
    sync:
      webhook:
        url: http://tuesdae.jberger.pl:3001/gateway/sync
